name: 🤔 Question or generic issue
description: Do you have a question? Or is it something else that doesn't fit one of the links below? Select this option!
labels: 'Needs: Triage'

body:
- type: markdown
  attributes:
    value: |
      This is for SharePoint development topics. If your submission is now about SharePoint development such as out-of-the-box capabilities, SharePoint configuration, please use refer to other support options listed on the [new issue chooser page](https://github.com/SharePoint/sp-dev-docs/issues/new/choose). Please provide as much information as possible so we can best address your submission. Thanks!

      - Follow our guidance on [How To Create Good Issues](https://github.com/sharepoint/sp-dev-docs/wiki/How-to-Create-Good-Issues).
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.

      Please provide the following details about your environment. 🚨  *If this section is ignored, your submission will be flagged as **incomplete** & automatically closed.*

- type: dropdown
  attributes:
    label: What type of issue is this?
    options:
      - Question
      - Documentation issue / typo
      - other
  validations:
    required: true

- type: dropdown
  attributes:
    label: What SharePoint development model, framework, SDK or API is this about?
    description: |
      What tooling, frameworks, SDKs, or official libraries is this related to? Please include the version details in the *"Additional environment details"* field below.

      **This form is only for officially supported Microsoft products**.

      *If your question is about a third-party or another library/SDK/tooling that is not officially supported by Microsoft, please submit your issue to that project's relevant forum.*

      **NOTE**:💥 If you select SharePoint Framework, you must include the following version numbers in the **Additional environment details** section below: 1️⃣  SharePoint Framework & 2️⃣  Node.js (`node -v`).
    options:
      - 💥 SharePoint Framework
      - SharePoint Add-ins
      - SharePoint CSOM
      - SharePoint REST API
      - Site designs & site scripts
      - Declarative list formatting
      - not applicable
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true

- type: dropdown
  attributes:
    label: Target SharePoint environment
    options:
      - SharePoint Online
      - SharePoint Server 2019 (on-premise)
      - SharePoint Server 2016 (on-premise)
      - other (enter in the "Additional environment details" area below)
  validations:
    required: true

- type: checkboxes
  attributes:
    label: What browser(s) / client(s) have you tested
    description: |
      Select the browser(s)/clients this submission is relevant to.

      **NOTE**:💥 If you select an item with this icon, you must include the version number of the selection in the **Additional environment details** section below.
    options:
      - label: 💥 Internet Explorer
      - label: 💥 Microsoft Edge
      - label: 💥 Google Chrome
      - label: 💥 FireFox
      - label: 💥 Safari
      - label: mobile (iOS/iPadOS)
      - label: mobile (Android)
      - label: not applicable
      - label: other (enter in the "Additional environment details" area below)

- type: textarea
  attributes:
    label: Additional environment details
    description: Include as much detail about the environment you're targetting. This is required if "other (enter below)" is selected in the previous field.
    value: |
      - browser version
      - SPFx version
      - Node.js version
      - etc

- type: textarea
  attributes:
    label: Issue description
  validations:
    required: true
